name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      # Step 3: Install dependencies
      - name: Install dependencies
        run: npm install

      # Step 4: Clean build folder
      - name: Clean build folder
        run: rm -rf dist

      # Step 5: Build project
      - name: Inject Token at Runtime
        run: echo "<script>window.REACT_APP_WORKDIARY_TOKEN='${{ secrets.REACT_APP_WORKDIARY_TOKEN }}';</script>" >> ./dist/index.html

      # Step 6: Debug environment variables (optional for debugging, remove in production)
      - name: Check .env
        run: cat .env

      # Step 7: Build project
      - name: Build project
        run: npm run build

      # Step 8: Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
