jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install

      - name: Clean build folder
        run: rm -rf dist
        
      - name: Inject API Key
        run: echo "REACT_APP_API_KEY=${{ secrets.REACT_APP_API_KEY }}" >> .env

      - name: Build project
        run: npm run build

      - name: Create CNAME file
        run: echo "www.mitjadragan.com" > ./dist/CNAME

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          force_orphan: true
